version: '3.8'

services:
  # CONFIG SERVER
  config-server:
    build:
      context: ./config-server
    image: lernjava-config-server
    container_name: config-server
    ports:
      - "8888:8888"
    environment:
      SPRING_CLOUD_CONFIG_SERVER_GIT_URI: file:///config-repo
    volumes:
      - ./config-repo:/config-repo
    networks:
      - app-network

  # EUREKA DISCOVERY
  discovery-service:
    build: ./discovery-service
    container_name: discovery-service
    ports:
      - "8761:8761"
    networks:
      - app-network

  # ZOOKEEPER
  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"
    networks:
      - app-network

  # KAFKA
  kafka:
    image: confluentinc/cp-kafka:7.5.0
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - app-network

  # POSTGRES DATABASE
  postgres-db:
    image: postgres:15
    container_name: postgres-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 61876187
      POSTGRES_DB: myDB
    ports:
      - "5433:5432"
    networks:
      - app-network

  # USER SERVICE
  user-service:
    build: ./
    container_name: user-service
    depends_on:
      - kafka
      - postgres-db
      - config-server
      - discovery-service
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-db:5432/myDB
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 61876187

      # Eureka
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discovery-service:8761/eureka/

      # Config server
      SPRING_CONFIG_IMPORT: optional:configserver:http://config-server:8888

      # Kafka
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    networks:
      - app-network
    ports:
      - "8080:8080"

  # NOTIFICATION SERVICE
  notification-service:
    build: ./notification-service
    container_name: notification-service
    depends_on:
      - kafka
      - config-server
      - discovery-service
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discovery-service:8761/eureka/
      SPRING_CONFIG_IMPORT: optional:configserver:http://config-server:8888
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    networks:
      - app-network
    ports:
      - "8090:8090"

  # GATEWAY
  gateway-service:
    build: ./gateway-service
    container_name: gateway-service
    depends_on:
      - user-service
      - notification-service
      - discovery-service
    environment:
      SPRING_CONFIG_IMPORT: optional:configserver:http://config-server:8888
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discovery-service:8761/eureka/
    ports:
      - "8083:8083"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge